customhost = "database-1.cix6hw6njem8.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "destiny232323"
customdb = "database-1"
custombucket = "yeeguantongawsbucket"
customregion = "us-east-1"
