customhost = "employee.cix6hw6njem8.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "destiny232323"
customdb = "employee"
custombucket = "yeeguantongawsbucket"
customregion = "us-east-1"
